### ISSUE TITLE
Plugin update needed for v5.6.0

### ISSUE THREAD

**Issue by craftzdog** [fkunn1326/inkdrop-spoiler#1]
Hi!

Thank you for creating such a cool plugin.
The desktop v5.6.0 is currently in beta, which comes with a new Markdown renderer.
Your plugin has to be updated to support it.
Please check out the following topic for more details:

https://forum.inkdrop.app/t/plugin-update-check-needed-for-supporting-v5-6-0/4117

Looks like you don't have an account on the user forum yet.
Can you please log in to it so that I can mention you on the forum?

**Comment by fkunn1326** [comment]
I finished updating it.

**Comment by craftzdog** [comment]
Thank you so much for updating!🙏
